version: "3"

services:
  
  mysql:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    image: mysql:5.6
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${OPENEDX_ELASTICSEARCH_PORT}:${OPENEDX_ELASTICSEARCH_PORT}"

  elasticsearch:
    image: edxops/elasticsearch:devstack
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - elasticsearch_data:/usr/share/elasticsearch/logs

  memcached:
    image: memcached:1.4.24

  discovery:
    command: bash -c 'source /edx/app/discovery/discovery_env && while true; do python /edx/app/discovery/discovery/manage.py runserver 0.0.0.0:18381; sleep 2; done'
    depends_on:
      - mysql
      - elasticsearch
      - memcached
    stdin_open: true
    tty: true
    environment:
      TEST_ELASTICSEARCH_URL: "http://elasticsearch:${OPENEDX_ELASTICSEARCH_PORT}"
      ENABLE_DJANGO_TOOLBAR: 1
    image: edxops/discovery:${OPENEDX_IMAGE_VERSION}
    ports:
      - "${OPENEDX_DISCOVERY_PORT}:${OPENEDX_DISCOVERY_PORT}"
    volumes:
      - discovery_assets:/edx/var/discovery/
